"""documents and chunks for rag

Revision ID: 8d097a61d75c
Revises: c87868dbd78b
Create Date: 2025-12-14 17:28:07.073635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '8d097a61d75c'
down_revision: Union[str, Sequence[str], None] = 'c87868dbd78b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('collection_id', sa.UUID(), nullable=False))
    op.add_column('chunks', sa.Column('chunk_index', sa.Integer(), nullable=False))
    op.add_column('chunks', sa.Column('embedding', Vector(dim=384), nullable=False))
    op.create_index(op.f('ix_chunks_collection_id'), 'chunks', ['collection_id'], unique=False)
    op.create_foreign_key(
        "fk_chunks_collection_id_collections",
        "chunks",
        "collections",
        ["collection_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_chunks_collection_id_collections", "chunks", type_="foreignkey")
    op.drop_index(op.f('ix_chunks_collection_id'), table_name='chunks')
    op.drop_column('chunks', 'embedding')
    op.drop_column('chunks', 'chunk_index')
    op.drop_column('chunks', 'collection_id')
    # ### end Alembic commands ###
